version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: pg-rotation-demo
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpw
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d app"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

